### ISSUE TITLE
Kafka Connect outputs DEBUG statements even though log is specified to info

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/cp-docker-images#181]
I tried launching the docker image, but I see a lot of DEBUG statements even though I asked for "INFO" level only.
This kind of DEBUG statements:

```
kafka-connect_1          | [2016-12-09 02:08:35,547] DEBUG could not scan file javax/annotation/meta/When.java in url file:/usr/shar
e/java/kafka-connect-hdfs/jsr305-1.3.9.jar with scanner TypeAnnotationsScanner (org.reflections.Reflections)
kafka-connect_1          | [2016-12-09 02:08:35,547] DEBUG could not scan file javax/annotation/meta/When.java in url file:/usr/shar
e/java/kafka-connect-hdfs/jsr305-1.3.9.jar with scanner SubTypesScanner (org.reflections.Reflections)
kafka-connect_1          | [2016-12-09 02:08:35,548] INFO Reflections took 6860 ms to scan 265 urls, producing 12684 keys and 83871
values  (org.reflections.Reflections)
kafka-connect_1          | [2016-12-09 02:08:38,004] DEBUG Received successful heartbeat response for group quickstart (org.apache.k
afka.clients.consumer.internals.AbstractCoordinator)
kafka-connect_1          | [2016-12-09 02:08:41,039] DEBUG Received successful heartbeat response for group quickstart (org.apache.k
afka.clients.consumer.internals.AbstractCoordinator)

kafka-connect_1          | [2016-12-09 02:08:44,083] DEBUG Received successful heartbeat response for group quickstart (org.apache.k
afka.clients.consumer.internals.AbstractCoordinator)
```

My compose config:
```

  kafka-connect:
    image: confluentinc/cp-kafka-connect:3.1.1
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka1:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "quickstart"
      CONNECT_CONFIG_STORAGE_TOPIC: "quickstart-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "quickstart-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "quickstart-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
    depends_on:
      - zoo1
      - kafka1
      - kafka-schema-registry
      - kafka-rest-proxy
```
