### ISSUE TITLE
Use docker HEALTHCHECK

### ISSUE THREAD

**Issue by blootsvoets** [confluentinc/cp-docker-images#248]
Unless there is absolutely no doubt that a service will exit whenever it stops listening to a public port, it might be good to add a health check to the service. By using the Dockerfile [HEALTHCHECK command](https://docs.docker.com/engine/reference/builder/#healthcheck), the status of a docker service is automatically monitored. It will exit the container for you if the service stops listening to its designated port. For the `kafka` container, for example, the command could be:

```dockerfile
HEALTHCHECK --interval=1m --timeout=3s \
   CMD nc -z localhost 9092 || exit 1
```

For a HTTP container like `schema-registry` it could be

```dockerfile
HEALTHCHECK --interval=1m --timeout=3s \
   CMD curl --fail http://localhost:8081/ || exit 1
```

Would this be something considering for the images in this repository? If not, would it be worth documenting the preferred health check for any given image in this repository?

**Comment by pratapagiri** [comment]
Any update on this feature? 
Could you please HEALTHCHECK feature for Kafka and Zookeer?

**Comment by osher** [comment]
If you don't want to add it to the Dockerfile, - then at least - please add it to your docs, so I can add it to my kubernetes and/or docker-compose definitions.

I've been trying to find a valid healthcheck command or a documentation about a healthcheck command, for no avail :( 

The proposed healthcheck above does not work for me :(

**Comment by rjacobs91** [comment]
```
version: "3.0"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    healthcheck:
      test: kafka-topics --bootstrap-server broker:9092 --list
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    healthcheck:
      test: curl --output /dev/null --silent --head --fail http://schema-registry:8081/subjects
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  rest-proxy:
    image: confluentinc/cp-kafka-rest
    depends_on:
      - broker
      - schema-registry
    healthcheck:
      test: curl --output /dev/null --silent --head --fail http://rest-proxy:8082
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8082:8082"
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
```
