### ISSUE TITLE
WARN DEPRECATION warning

### ISSUE THREAD

**Issue by Ox24** [confluentinc/cp-docker-images#249]
Hi there,

i get this error message if i try to change the port of the control-center 

> WARN DEPRECATION warning: `listeners` configuration is not configured.

```
control-center:
    image: confluentinc/cp-enterprise-control-center
    hostname: control-center
    depends_on:
      - zookeeper
      - broker
      - schema_registry
      - connect
    ports:
      - '9021:10003'
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:10001'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      PORT: 10003

```
after checking the sources under `rest-utils/core/src/main/java/io/confluent/rest/Application.java` seems like port changing doesn't have any affect on it. It still starts the jetty on 9021 ...
