### ISSUE TITLE
Adding custom connector to cp-all-in-one image

### ISSUE THREAD

**Issue by buinauskasevaldas** [confluentinc/cp-docker-images#333]
I'm trying to register https://github.com/jcustenborder/kafka-connect-cdc-mssql connector using `CLASSPATH`.

I altered my `docker-compose.yml` file and added these two lines:

    volumes:
      - ./jars:/etc/kafka-connect/jars/

JARs appear in Docker image in this folder: /etc/kafka-connect/jars/kafka-connect-cdc-mssql however if I navigate to http://localhost:8083/connector-plugins to get list of available connectors, mine doesn't appear there.

What's the right way to add a custom jar to my Connect image?

**Comment by ewencp** [comment]
cc @confluentinc/connect

**Comment by buinauskasevaldas** [comment]
I actually managed to resolve this. Like previously, I've mounted my custom path:
```yaml
volumes:
  - ./jars:/etc/kafka-connect/jars/
```

And then added an extra environment variable:
````yaml
CONNECT_PLUGIN_PATH: '/etc/kafka-connect/jars'
````

So the final result is:
```yaml
connect:
  image: confluentinc/cp-kafka-connect
  hostname: connect
  depends_on:
    - zookeeper
    - broker
    - schema_registry
  ports:
    - 8083:8083
  volumes:
    - ./jars:/etc/kafka-connect/jars/
  environment:
    CONNECT_BOOTSTRAP_SERVERS: 'broker:9092'
    CONNECT_REST_ADVERTISED_HOST_NAME: connect
    CONNECT_REST_PORT: 8083
    CONNECT_GROUP_ID: compose-connect-group
    CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
    CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
    CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
    CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
    CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
    CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
    CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
    CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
    CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
    CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
    CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
    CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    CONNECT_PLUGIN_PATH: '/etc/kafka-connect/jars'
```

Then my plugin got registered.
