### ISSUE TITLE
Add optional ENV overrides both in build arg and arg for CMD

### ISSUE THREAD

**Issue by mikesparr** [confluentinc/cp-docker-images#398]
See pull request and merge: https://github.com/confluentinc/cp-docker-images/pull/397

Kubernetes doesn't allow dynamically-created concat params in `env` configs to allow dynamic assignment of Pod IPs for `KAFKA_ADVERTISED_LISTENERS` ENV setting. Even though the image deploys and runs, without the pod-specific IPs it prevents other clients from interacting with brokers. Given so many issues and workarounds to get Kafka and ZK to work in Kubernetes, there are some simple tweaks we can make to the image and run script to add flexibility without impacting any existing usage. 

Kubernetes does has the ability to declare `args` and these are appended to the `CMD` ran in container (if you do not override the `command`). The premise of this PR is simple, check for optional args added to CMD and if they exist, loop through them and export their values as environment variables.

## Example (relevant snippet) Kubernetes StatefulSet usage
```
      containers:
      - name: cp-kafka
        imagePullPolicy: Always
        image: confluentinc/cp-kafka:3.3.1
        resources:
          requests:
            memory: "4Gi"
            cpu: 0.5
        ports:
        - containerPort: 9092
          name: server
          protocol: TCP
        - containerPort: 49999
          name: jmx
          protocol: TCP
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "export KAFKA_BROKER_ID=${HOSTNAME##*-}"
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zk-cs.default.svc.cluster.local:2181
          - name: KAFKA_JMX_PORT
            value: "49999"
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        args:
          - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$(MY_POD_IP):9092"
```
