### ISSUE TITLE
Setting SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR

### ISSUE THREAD

**Issue by zoltan-fedor** [confluentinc/cp-docker-images#448]
Settings SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR doesn't work:

Dockerfile:
```
  schema_registry:
    image: confluentinc/cp-schema-registry:4.0.0-3
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
```

Container log:
`WARN The configuration 'topic.replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)`

The kafkastore.topic.replication.factor is an existing config value, see https://docs.confluent.io/current/schema-registry/docs/config.html

The same works for some other config values, like SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
