### ISSUE TITLE
[OCP] 4.1.0 fails on startup

### ISSUE THREAD

**Issue by angelbarrera92** [confluentinc/cp-docker-images#461]
Hi

We're trying to deploy zookeeper in openshift. Version 4.0.0 works perfectly for us but trying to upgrade to version 4.1.0 fails to start. 

Paste the log output:
```bash
+ '[' -z '' ']'
+ ID_OFFSET=1
+ export ZOOKEEPER_SERVER_ID=1
+ ZOOKEEPER_SERVER_ID=1
++ cat /var/run/secrets/kubernetes.io/serviceaccount/namespace
+ export PROJECT=confluent
+ PROJECT=confluent
+ export 'ZOOKEEPER_SERVERS=ox-zookeeper-410-0.ox-zookeeper-410-headless.confluent.svc:2888:3888;ox-zookeeper-410-1.ox-zookeeper-410-headless.confluent.svc:2888:3888;ox-zookeeper-410-2.ox-zookeeper-410-headless.confluent.svc:2888:3888'
+ ZOOKEEPER_SERVERS='ox-zookeeper-410-0.ox-zookeeper-410-headless.confluent.svc:2888:3888;ox-zookeeper-410-1.ox-zookeeper-410-headless.confluent.svc:2888:3888;ox-zookeeper-410-2.ox-zookeeper-410-headless.confluent.svc:2888:3888'
+ /etc/confluent/docker/run

echo "===> ENV Variables ..."
+ echo '===> ENV Variables ...'
env | sort
===> ENV Variables ...
+ env
+ sort
ALLOW_UNSIGNED=false
APPLICATION_NAME=ox-zookeeper-410
COMPONENT=zookeeper
CONFLUENT_DEB_VERSION=1
CONFLUENT_MAJOR_VERSION=4
CONFLUENT_MINOR_VERSION=1
CONFLUENT_MVN_LABEL=
CONFLUENT_PATCH_VERSION=0
CONFLUENT_PLATFORM_LABEL=
CONFLUENT_VERSION=4.1.0
CUB_CLASSPATH=/etc/confluent/docker/docker-utils.jar
HOME=/
HOSTNAME=ox-zookeeper-410-0
KAFKA_VERSION=1.1.0
KUBERNETES_PORT=tcp://172.30.0.1:443
KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443
KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_53_TCP=tcp://172.30.0.1:53
KUBERNETES_PORT_53_TCP_ADDR=172.30.0.1
KUBERNETES_PORT_53_TCP_PORT=53
KUBERNETES_PORT_53_TCP_PROTO=tcp
KUBERNETES_PORT_53_UDP=udp://172.30.0.1:53
KUBERNETES_PORT_53_UDP_ADDR=172.30.0.1
KUBERNETES_PORT_53_UDP_PORT=53
KUBERNETES_PORT_53_UDP_PROTO=udp
KUBERNETES_SERVICE_HOST=172.30.0.1
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_DNS=53
KUBERNETES_SERVICE_PORT_DNS_TCP=53
KUBERNETES_SERVICE_PORT_HTTPS=443
LANG=C.UTF-8
OX_KAFKA_CONTROL_CENTER_PORT=tcp://172.30.201.6:9021
OX_KAFKA_CONTROL_CENTER_PORT_9021_TCP=tcp://172.30.201.6:9021
OX_KAFKA_CONTROL_CENTER_PORT_9021_TCP_ADDR=172.30.201.6
OX_KAFKA_CONTROL_CENTER_PORT_9021_TCP_PORT=9021
OX_KAFKA_CONTROL_CENTER_PORT_9021_TCP_PROTO=tcp
OX_KAFKA_CONTROL_CENTER_SERVICE_HOST=172.30.201.6
OX_KAFKA_CONTROL_CENTER_SERVICE_PORT=9021
OX_KAFKA_CONTROL_CENTER_SERVICE_PORT_SERVER=9021
OX_KAFKA_PORT=tcp://172.30.227.70:9092
OX_KAFKA_PORT_9092_TCP=tcp://172.30.227.70:9092
OX_KAFKA_PORT_9092_TCP_ADDR=172.30.227.70
OX_KAFKA_PORT_9092_TCP_PORT=9092
OX_KAFKA_PORT_9092_TCP_PROTO=tcp
OX_KAFKA_REST_PROXY_PORT=tcp://172.30.145.15:8082
OX_KAFKA_REST_PROXY_PORT_8082_TCP=tcp://172.30.145.15:8082
OX_KAFKA_REST_PROXY_PORT_8082_TCP_ADDR=172.30.145.15
OX_KAFKA_REST_PROXY_PORT_8082_TCP_PORT=8082
OX_KAFKA_REST_PROXY_PORT_8082_TCP_PROTO=tcp
OX_KAFKA_REST_PROXY_SERVICE_HOST=172.30.145.15

echo "===> User"
+ echo '===> User'
id
+ id
OX_KAFKA_REST_PROXY_SERVICE_PORT=8082
OX_KAFKA_REST_PROXY_SERVICE_PORT_SERVER=8082
OX_KAFKA_SCHEMA_REGISTRY_PORT=tcp://172.30.74.255:8081
OX_KAFKA_SCHEMA_REGISTRY_PORT_8081_TCP=tcp://172.30.74.255:8081
OX_KAFKA_SCHEMA_REGISTRY_PORT_8081_TCP_ADDR=172.30.74.255
OX_KAFKA_SCHEMA_REGISTRY_PORT_8081_TCP_PORT=8081
OX_KAFKA_SCHEMA_REGISTRY_PORT_8081_TCP_PROTO=tcp
OX_KAFKA_SCHEMA_REGISTRY_SERVICE_HOST=172.30.74.255
OX_KAFKA_SCHEMA_REGISTRY_SERVICE_PORT=8081
OX_KAFKA_SCHEMA_REGISTRY_SERVICE_PORT_SERVER=8081
OX_KAFKA_SERVICE_HOST=172.30.227.70
OX_KAFKA_SERVICE_PORT=9092
OX_KAFKA_SERVICE_PORT_CLIENT=9092
OX_ZOOKEEPER400_PORT=tcp://172.30.236.246:2181
OX_ZOOKEEPER400_PORT_2181_TCP=tcp://172.30.236.246:2181
OX_ZOOKEEPER400_PORT_2181_TCP_ADDR=172.30.236.246
OX_ZOOKEEPER400_PORT_2181_TCP_PORT=2181
OX_ZOOKEEPER400_PORT_2181_TCP_PROTO=tcp
OX_ZOOKEEPER400_SERVICE_HOST=172.30.236.246
OX_ZOOKEEPER400_SERVICE_PORT=2181
OX_ZOOKEEPER400_SERVICE_PORT_CLIENT=2181
OX_ZOOKEEPER410_PORT=tcp://172.30.196.238:2181
OX_ZOOKEEPER410_PORT_2181_TCP=tcp://172.30.196.238:2181
OX_ZOOKEEPER410_PORT_2181_TCP_ADDR=172.30.196.238
OX_ZOOKEEPER410_PORT_2181_TCP_PORT=2181
OX_ZOOKEEPER410_PORT_2181_TCP_PROTO=tcp
OX_ZOOKEEPER410_SERVICE_HOST=172.30.196.238
OX_ZOOKEEPER410_SERVICE_PORT=2181
OX_ZOOKEEPER410_SERVICE_PORT_CLIENT=2181
OX_ZOOKEEPER_410_2_PORT=tcp://172.30.233.82:2181
OX_ZOOKEEPER_410_2_PORT_2181_TCP=tcp://172.30.233.82:2181
OX_ZOOKEEPER_410_2_PORT_2181_TCP_ADDR=172.30.233.82
OX_ZOOKEEPER_410_2_PORT_2181_TCP_PORT=2181
OX_ZOOKEEPER_410_2_PORT_2181_TCP_PROTO=tcp
OX_ZOOKEEPER_410_2_SERVICE_HOST=172.30.233.82
OX_ZOOKEEPER_410_2_SERVICE_PORT=2181
OX_ZOOKEEPER_410_2_SERVICE_PORT_CLIENT=2181
OX_ZOOKEEPER_410_PORT=tcp://172.30.232.125:2181
OX_ZOOKEEPER_410_PORT_2181_TCP=tcp://172.30.232.125:2181
OX_ZOOKEEPER_410_PORT_2181_TCP_ADDR=172.30.232.125
OX_ZOOKEEPER_410_PORT_2181_TCP_PORT=2181
OX_ZOOKEEPER_410_PORT_2181_TCP_PROTO=tcp
OX_ZOOKEEPER_410_SERVICE_HOST=172.30.232.125
OX_ZOOKEEPER_410_SERVICE_PORT=2181
OX_ZOOKEEPER_410_SERVICE_PORT_CLIENT=2181
OX_ZOOKEEPER_PORT=tcp://172.30.58.139:2181
OX_ZOOKEEPER_PORT_2181_TCP=tcp://172.30.58.139:2181
OX_ZOOKEEPER_PORT_2181_TCP_ADDR=172.30.58.139
OX_ZOOKEEPER_PORT_2181_TCP_PORT=2181
OX_ZOOKEEPER_PORT_2181_TCP_PROTO=tcp
OX_ZOOKEEPER_SERVICE_HOST=172.30.58.139
OX_ZOOKEEPER_SERVICE_PORT=2181
OX_ZOOKEEPER_SERVICE_PORT_CLIENT=2181
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PROJECT=confluent
PWD=/
PYTHON_PIP_VERSION=8.1.2
PYTHON_VERSION=2.7.9-1
SCALA_VERSION=2.11
SHLVL=2
ZOOKEEPER_CLIENT_PORT=2181
ZOOKEEPER_INIT_LIMIT=5
ZOOKEEPER_SERVERS=ox-zookeeper-410-0.ox-zookeeper-410-headless.confluent.svc:2888:3888;ox-zookeeper-410-1.ox-zookeeper-410-headless.confluent.svc:2888:3888;ox-zookeeper-410-2.ox-zookeeper-410-headless.confluent.svc:2888:3888
ZOOKEEPER_SERVER_ID=1
ZOOKEEPER_SYNC_LIMIT=2
ZOOKEEPER_TICK_TIME=2000
ZULU_OPENJDK_VERSION=8=8.17.0.3
_=/usr/bin/env
===> User
uid=1000140000 gid=0(root) groups=0(root),1000140000

echo "===> Configuring ..."
+ echo '===> Configuring ...'
/etc/confluent/docker/configure
+ /etc/confluent/docker/configure
===> Configuring ...


dub ensure ZOOKEEPER_CLIENT_PORT
+ dub ensure ZOOKEEPER_CLIENT_PORT

dub path /etc/kafka/ writable
+ dub path /etc/kafka/ writable

# myid is required for clusters
if [[ -n "${ZOOKEEPER_SERVERS-}" ]]
then
  dub ensure ZOOKEEPER_SERVER_ID
  export ZOOKEEPER_INIT_LIMIT=${ZOOKEEPER_INIT_LIMIT:-"10"}
  export ZOOKEEPER_SYNC_LIMIT=${ZOOKEEPER_SYNC_LIMIT:-"5"}
fi
+ [[ -n ox-zookeeper-410-0.ox-zookeeper-410-headless.confluent.svc:2888:3888;ox-zookeeper-410-1.ox-zookeeper-410-headless.confluent.svc:2888:3888;ox-zookeeper-410-2.ox-zookeeper-410-headless.confluent.svc:2888:3888 ]]
+ dub ensure ZOOKEEPER_SERVER_ID
+ export ZOOKEEPER_INIT_LIMIT=5
+ ZOOKEEPER_INIT_LIMIT=5
+ export ZOOKEEPER_SYNC_LIMIT=2
+ ZOOKEEPER_SYNC_LIMIT=2

if [[ -n "${ZOOKEEPER_SERVER_ID-}" ]]
then
  dub template "/etc/confluent/docker/myid.template" "/var/lib/${COMPONENT}/data/myid"
fi
+ [[ -n 1 ]]
+ dub template /etc/confluent/docker/myid.template /var/lib/zookeeper/data/myid
[Errno 13] Permission denied: '/var/lib/zookeeper/data/myid'
Command [/usr/local/bin/dub template /etc/confluent/docker/myid.template /var/lib/zookeeper/data/myid] FAILED !
```

With version 4.0.0 we have no problems. Is there anything different between these versions that might affect the boot of the containers?

Best regards!

**Comment by gAmUssA** [comment]
@angelbarrera92 could you share yml file?

**Comment by angelbarrera92** [comment]
Sure!

```yaml
apiVersion: v1
kind: Template
labels:
  template: zookeeper
metadata:
  annotations:
    description: Zookeeper Deployment and Runtime Components
    iconClass: icon-java
    tags: java,zookeeper
  name: zookeeper
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-headless
  spec:
    clusterIP: None
    portalIP: None
    ports:
    - name: server
      port: 2888
      protocol: TCP
      targetPort: 2888
    - name: leader-election
      port: 3888
      protocol: TCP
      targetPort: 3888
    selector:
      application: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: 2181
    selector:
      application: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  data:
    init.sh: |-
      #!/bin/bash
      set -x

      [ -z "$ID_OFFSET" ] && ID_OFFSET=1
      export ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-} + $ID_OFFSET))
      export PROJECT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
      export ZOOKEEPER_SERVERS="${APPLICATION_NAME}-0.${APPLICATION_NAME}-headless.${PROJECT}.svc:2888:3888;${APPLICATION_NAME}-1.${APPLICATION_NAME}-headless.${PROJECT}.svc:2888:3888;${APPLICATION_NAME}-2.${APPLICATION_NAME}-headless.${PROJECT}.svc:2888:3888"
      /etc/confluent/docker/run
    client_port: '2181'
    tick_time: '2000'
    init_limit: '5'
    sync_limit: '2'
  kind: ConfigMap
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-config
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 3
    selector:
      matchLabels:
        application: ${APPLICATION_NAME}
    serviceName: ${APPLICATION_NAME}-headless
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: ${APPLICATION_NAME}
      spec:
        containers:
        - command: ['/bin/bash', '/etc/scripts/init.sh']
          env:
          - name: APPLICATION_NAME
            value: ${APPLICATION_NAME}
          - name: ZOOKEEPER_CLIENT_PORT
            valueFrom:
              configMapKeyRef:
                key: client_port
                name: ${APPLICATION_NAME}-config
          - name: ZOOKEEPER_TICK_TIME
            valueFrom:
              configMapKeyRef:
                key: tick_time
                name: ${APPLICATION_NAME}-config
          - name: ZOOKEEPER_INIT_LIMIT
            valueFrom:
              configMapKeyRef:
                key: init_limit
                name: ${APPLICATION_NAME}-config
          - name: ZOOKEEPER_SYNC_LIMIT
            valueFrom:
              configMapKeyRef:
                key: sync_limit
                name: ${APPLICATION_NAME}-config
          image: docker-registry.default.svc:5000/confluent/cp-zookeeper:${ZOOKEEPER_VERSION}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 2181
            name: client
            protocol: TCP
          - containerPort: 2888
            name: server
            protocol: TCP
          - containerPort: 3888
            name: leader-election
            protocol: TCP
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/zookeeper/data
            name: datadir
          - mountPath: /etc/scripts
            name: config
        volumes:
        - name: config
          configMap:
            name: ${APPLICATION_NAME}-config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
    volumeClaimTemplates:
    - metadata:
        labels:
          application: ${APPLICATION_NAME}
        name: datadir
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: zookeeper
- description: Zookeeper ImageStream Tag
  name: ZOOKEEPER_VERSION
  required: true
  value: 4.0.0
```
oc apply -f template.yml
oc new-app --template=zookeeper --param=APPLICATION_NAME=ox-zookeeper --param=ZOOKEEPER_VERSION=4.1.0

Thanks in advance @gAmUssA
