### ISSUE TITLE
After rebooting brokers and zookeeper, topics are deleted

### ISSUE THREAD

**Issue by joselmh** [confluentinc/cp-docker-images#674]
I'm running confluent kafka and zookeeper images on a four nodes Kubernetes cluster. One for zookeeper, and one for each of the three kafka brokers.
I'm using Stateful Sets for that with their correspondent Persistent Volume Claims.
I can create some topics, publish and consume messages on them normally.
Buy after rebooting the virtual machines, all topics are gone and, in /var/lib/kafka/data there are only files of a fresh installation files:

```
 root@kafka2-0:/var/lib/kafka# cd /var/lib/kafka/data/
 root@kafka2-0:/var/lib/kafka/data# ls -lrt
 total 4
   -rw-r--r-- 1 root root  0 Jan 23 09:50 recovery-point-offset-checkpoint
   -rw-r--r-- 1 root root  0 Jan 23 09:50 log-start-offset-checkpoint
   -rw-r--r-- 1 root root  0 Jan 23 09:50 cleaner-offset-checkpoint
   -rw-r--r-- 1 root root  0 Jan 23 09:50 replication-offset-checkpoint
   -rw-r--r-- 1 root root 54 Jan 23 09:50 meta.properties
```

No consumer_offsets, no partitions.

If I just restart the three bokers nodes, /var/lib/kafka/data dir on each of the brokers are full (consumer_offsets and partitions) but I'm not able to consume messages from the topics.

Here is the zookeeper descriptor:

 
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper # has to match .spec.template.metadata.labels
  serviceName: "zookeeper"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: zookeeper # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        name: zookeeper
        image: confluentinc/cp-zookeeper:5.0.1
        ports:
        - containerPort: 2181
        volumeMounts:
        - mountPath: /var/lib/zookeeper/
          name: zookeeper-volume-claim
      nodeSelector:
        noderole: zookeeper
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-volume-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "azure-disk"
      resources:
        requests:
          storage: 8Gi
```

and one broker descriptor (the others two brokers descriptors are the same but referencing broker2 and broker3)

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka1
spec:
  selector:
    matchLabels:
      app: kafka1 # has to match .spec.template.metadata.labels
  serviceName: "kafka1"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: kafka1 # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - env:
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://104.210.3.9:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.0.198.236:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        name: kafka1
        image: confluentinc/cp-enterprise-kafka:5.0.1
        ports:
        - containerPort: 9092
        volumeMounts:
        - mountPath: /var/lib/kafka
          name: kafka1-volume-claim
      nodeSelector:
        noderole: kafka1
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: kafka1-volume-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "azure-disk"
      resources:
        requests:
          storage: 8Gi
```

I assume that it's not a problem with persistent volumes, since I create a file in the mounted dir (/var/lib/kafka) and after restart, the file is still there.

Any idea what is happening?
