### ISSUE TITLE
Unable to bring up schema registry with ssl and sasl enabled with external kafka

### ISSUE THREAD

**Issue by arvindeybram** [confluentinc/cp-docker-images#724]
I tried bringing up schema registry with ssl and sasl enabled, I used an external kafka that has been brought up with ssl and sasl.

However, It is failing.

The configuration of schema registry is:

```
sasl:
  enable: true
  mechanism: "GSSAPI"
  scram:
    enabled: false
  krb:
    krbConf: <base64 of krb5.conf>
    krbSecretName: krb-admin-pass-anm
    krbPrincipalKey: krbPrincipalKey
    krbPasswordKey: krbPasswordKey
    krbRealm: "EXAMPLE.COM"

external_kafka:
      enabled: true
      BootStrapServers:
         fullServiceNameOverride: "SASL_SSL://kf-devopskafka-0.kf-devopskafka-headless.default.svc.cluster.local:9092"
      ZookeeperUrl:
         fullServiceNameOverride: ""

sr_ssl:
  enabled: true
  secret_name: ssl-schema-server-anm
  keystore_key: keyStore
  truststore_key: trustStore
  truststore_passwd_key: trustStorePass
  keystore_passwd_key: keyPass
  keystore_key_passwd_key: keyStorePass

kafkastore_ssl:
  enabled: true
  secret_name: ssl-kafka-client-anm
  keystore_key: keyStore
  truststore_key: trustStore
  truststore_passwd_key: trustStorePass
  keystore_passwd_key: keyStorePass
  keystore_key_passwd_key: keyPass
```

The error I can see in the log is:

[main] ERROR io.confluent.admin.utils.ClusterStatus - Error while getting broker list.
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:213)
        at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:148)
        at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:150)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
[main] INFO io.confluent.admin.utils.ClusterStatus - Expected 1 brokers but found only 0. Trying to query Kafka for metadata again ...
[main] ERROR io.confluent.admin.utils.ClusterStatus - Expected 1 brokers but found only 0. Brokers found [].
