### ISSUE TITLE
Having trouble enabling JMX for Zookeeper docker container

### ISSUE THREAD

**Issue by DaveSlinn** [confluentinc/cp-docker-images#739]
We have specified the KAFKA_JMX_PORT and KAFKA_JMX_HOSTNAME environment variables, and the container starts and zookeeper seems happy (the ruok is good and we can run zookeeper-shell and browse the nodes). But when bash into the container and run ``curl localhost:39999/metrics``, we get a ``(52) Empty reply from server``.   Or, is there another way to confirm that the metrics are accessible when zookeeper is running?

I've also tried searching the container for any .jar file with jmx in it's name, and nothing has appeared. Do we need to add one?

Is there an additional step to specify a list of metrics we want published?  Forgive, I'm new to both kafka and jmx metrics.

**Comment by cricket007** [comment]
JMX Metrics aren't exposed over HTTP (so curl won't work). 

You would have to use `jconsole` or VisualVM to inspect them

Or you would have to add something like Jolokia or Promethetus JMX exporter JARs if you did want HTTP-based JMX metrics

**Comment by DaveSlinn** [comment]
I don't think that is true.  I had forgotten I had posted this, and we've did eventually figure it out and we now have our JMX metrics available to prometheus.  Here is a sample of the metrics I can view from my console using curl:
```
[root@kafka02 td-agent]# curl localhost:39999/metrics                                                                                                                                                                                                                           # HELP jmx_config_reload_success_total Number of times configuration have successfully been reloaded.
# TYPE jmx_config_reload_success_total counter
jmx_config_reload_success_total 0.0
# HELP jvm_memory_bytes_used Used bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 2.72237216E8
jvm_memory_bytes_used{area="nonheap",} 2.3597624E7
# HELP jvm_memory_bytes_committed Committed (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_committed gauge
jvm_memory_bytes_committed{area="heap",} 5.36870912E8
jvm_memory_bytes_committed{area="nonheap",} 2.490368E7
# HELP jvm_memory_bytes_max Max (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_max gauge
jvm_memory_bytes_max{area="heap",} 5.36870912E8
jvm_memory_bytes_max{area="nonheap",} -1.0
# HELP jvm_memory_bytes_init Initial bytes of a given JVM memory area.
```
If I recall correctly, the missing ingredient to get this to work was in the KAFKA_OPTS environment variable.  This is what we ended up with in our docker-compose:
```
services:
  zookeeper:
    environment:
      KAFKA_OPTS: -Djava.rmi.server.hostname=kafka01 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=39998 -Dcom.sun.management.jmxremote.port=39998 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -javaagent:/etc/zookeeper/jmx/jmx_prometheus_javaagent-0.11.0.jar=39999:/etc/zookeeper/jmx/jmx-zookeeper-prometheus.yaml
```
where the jmx-zookeeper-prometheus.yaml was
```

    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
    - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+)><>(\\w+)"
      name: "cp_zookeeper_$2"
    - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+)><>(\\w+)"
      name: "cp_zookeeper_$3"
      labels:
        replicaId: "$2"
    - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(\\w+)"
      name: "cp_zookeeper_$4"
      labels:
        replicaId: "$2"
        memberType: "$3"
    - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+), name3=(\\w+)><>(\\w+)"
      name: "cp_zookeeper_$4_$5"
      labels:
        replicaId: "$2"
        memberType: "$3"
```
