### ISSUE TITLE
Kafka image is listening on unneeded ports. 

### ISSUE THREAD

**Issue by jcustenborder** [confluentinc/cp-docker-images#74]
Here is the snippit from my compose. 

```
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "confluent:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.99.101:9092"
```

`docker ps -a` yields.

```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                  NAMES
93247ce0c323        confluentinc/cp-kafka       "/etc/confluent/docke"   16 seconds ago      Up 15 seconds       2181/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:9092->9092/tcp   kafkaconnectsalesforce_kafka_1
```

Notice 2181, 2888, 3888 are exposed.
