### ISSUE TITLE
Inconvenient environment variable bug

### ISSUE THREAD

**Issue by kenpachiii** [confluentinc/cp-docker-images#779]
In kubernetes if you happen to define a service with the following settings:

```
apiVersion: v1
    kind: Service
metadata:
  name: kafka 
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
```
Will create an environment variable being set by kubernetes with the key KAFKA_PORT causing the docker image to exit with code 1 because of this block of code

```
if [[ -n "${KAFKA_PORT-}" ]]
then
  echo "port is deprecated. Please use KAFKA_ADVERTISED_LISTENERS instead."
  exit 1
fi
```
defined in the configure script.
