### ISSUE TITLE
Missing configuration KAFKA_REST_ZOOKEEPER_CONNECT on docker-compose

### ISSUE THREAD

**Issue by frenkelor** [confluentinc/cp-docker-images#787]
kafka-rest service is unable to connect to zookeeper and exist on time out.

`Zookeeper error: Unable to connect to zookeeper server \‘\’ with timeout of 6000 ms’`

the solution is to add KAFKA_REST_ZOOKEEPER_CONNECT with zookeeper host
add to `/examples/cp-all-in-one/docker-compose.yml`
`KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'`

example:

```
rest-proxy:
    image: confluentinc/cp-kafka-rest:5.3.0
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      KAFKACLIENT_ZK_SESSION_TIMEOUT_MS_CONFIG: 30000
```
