### ISSUE TITLE
Kafka Connect JMX : source & sink task metrics missing for tasks in failed state

### ISSUE THREAD

**Issue by mikouaj** [confluentinc/cp-docker-images#808]
## Overview
Kafka Connect exposes various metrics via JMX. Those metrics can be exported i.e. by _Prometheus JMX Exporter_ for further processing.

One of crucial attributes is connector's **task status**. According to official Kafka docs, status is available as *status* attribute of following MBean:
> kafka.connect:type=connector-task-metrics,connector="{connector}",task="{task}"
> status - The status of the connector task. One of 'unassigned', 'running', 'paused', 'failed', or 'destroyed'.

## Issue
Generally `connector-task-metrics` are exposed propery for tasks in `running` status but not exposed at all if task is `failed`.

Failed Task **appears** properly with failed status when queried via **REST API**:
```
$ curl -X GET -u 'user:pass' http://kafka-connect.mydomain.com/connectors/customerconnector/status
{"name":"customerconnector","connector":{"state":"RUNNING","worker_id":"kafka-connect.mydomain.com:8080"},"tasks":[{"id":0,"state":"FAILED","worker_id":"kafka-connect.mydomain.com:8080","trace":"org.apache.kafka.connect.errors.ConnectException: Received DML 'DELETE FROM mysql.rds_sysinfo ......"}],"type":"source"}
```

Failed Task **doesn't appear** as bean with `connector-task-metrics` type when queried via **JMX**:
```
$ echo "beans -d kafka.connect" | java -jar target/jmxterm-1.1.0-SNAPSHOT-uber.jar -l localhost:8081 -n -v silent | grep connector=customerconnector
kafka.connect:connector=customerconnector,task=0,type=task-error-metrics
kafka.connect:connector=customerconnector,type=connector-metrics
$
```
## Expected result
It is expected, that bean with `connector-task-metrics` type will appear also for tasks that failed.

Below is example of how beans are properly registered for tasks in Running state:
```
$ echo "get -b kafka.connect:connector=sinkConsentSubscription-1000,task=0,type=connector-task-metrics status" | java -jar target/jmxterm-1.1.0-SNAPSHOT-ube r.jar -l localhost:8081 -n -v silent
status = running;
$
```

**Comment by iMajna** [comment]
Meeting with the same issue. Monitoring task statuses is really crucial for me!

**Comment by l0n3r4n83r** [comment]
We have seen issues where the JMX metrics are not published or sometimes disappear and we need to restart the connect cluster for them to appear again. This leads to false alerts in our monitoring system

**Comment by bmoe24x** [comment]
Has anybody found a workaround to this? Seems like a pretty significant operational issue... especially when trying to utilize Prometheus and AlertManager. The REST API gives back a FAILED status when a task fails but JMX does not... Would be very very handy for both situations to match

**Comment by l0n3r4n83r** [comment]
@bmoe24x it's not ideal but we alert on missing data when a task/connector fails the jmx metrics stop publishing

**Comment by bmoe24x** [comment]
> @bmoe24x it's not ideal but we alert on missing data when a task/connector fails the jmx metrics stop publishing

So you essentially set up an alert that triggers when that metric is missing?

**Comment by l0n3r4n83r** [comment]
> > @bmoe24x it's not ideal but we alert on missing data when a task/connector fails the jmx metrics stop publishing
> 
> So you essentially set up an alert that triggers when that metric is missing?

Yes

**Comment by strigona-worksight** [comment]
This issue is being addressed in Kafka here: https://github.com/apache/kafka/pull/8502 and tracked here: https://issues.apache.org/jira/browse/KAFKA-9066

I don't see an ETA yet.

**Comment by bmoe24x** [comment]
> > > @bmoe24x it's not ideal but we alert on missing data when a task/connector fails the jmx metrics stop publishing
> > 
> > 
> > So you essentially set up an alert that triggers when that metric is missing?
> 
> Yes

Thanks for the idea!

As for everyone else, thanks to @mikouaj there is a [Jira issue here](https://issues.apache.org/jira/browse/KAFKA-9066)

...and a pull request with some recent traction thanks to @C0urante [found here](https://github.com/apache/kafka/pull/8502) Would love to get this included in the next release, would save a lot of effort on a hacky solution!

**Comment by bmoe24x** [comment]
> This issue is being addressed in Kafka here: [apache/kafka#8502](https://github.com/apache/kafka/pull/8502) and tracked here: https://issues.apache.org/jira/browse/KAFKA-9066
> 
> I don't see an ETA yet.

Beat me to it by 13 seconds it looks like! Lets hope this functionality gets pulled in soon 🤞

**Comment by Dujma** [comment]
Even though this is fixed in the Kafka version, does it also needs to be fixed for Connect? I'm still seeing the same issue with latest version of Kafka.

**Comment by C0urante** [comment]
@Dujma this should be fixed for every version of Connect that has the changes from https://github.com/apache/kafka/pull/8502. If you're still seeing it, can you provide steps to reproduce?

**Comment by Dujma** [comment]
We are running our Kafka in Confluent Cloud (Confluent Platform 7.0.0). We are using Kafka Connect Docker cp-kafka-connect-base:5.5.0 which is running in k8s cluster. We have Prometheus operator running in the k8s cluster and metrics are picked up by NewRelic agent.

Here's the JMX configuration for Kafka Connect:

```yaml
jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:5555/jmxrmi
lowercaseOutputName: true
lowercaseOutputLabelNames: true
ssl: false
rules:
- pattern : "kafka.connect<type=connect-worker-metrics>([^:]+):"
  name: "cp_kafka_connect_worker_$1"
- pattern : "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
  name: "cp_kafka_connect_$1_$2"
- pattern : "kafka.producer<type=producer-metrics, client-id=(.+)><>(.+):\\w*"
  name: "cp_kafka_connect_producer_$2"
- pattern : "kafka.consumer<type=consumer-metrics, client-id=(.+)><>(.+):\\w*"
  name: "cp_kafka_connect_consumer_$2"
- pattern : "kafka.consumer<type=consumer-fetch-manager-metrics, client-id=([-.w]+), topic=([-.w]+)><>(.+):\\w*"
  name: "cp_kafka_connect_consumer_fetch_$2"
  labels:
    topic: "$3"
- pattern : "kafka.connect<type=connector-task-metrics, connector=([^:]+), task=([^:]+)><>status: ([^:]+)"
  name: "cp_kafka_connect_connect_connector_metrics"
  value: 1
  labels:
    connector: $1
    task: $2
    status: $3
```
When I try to query the metrics in NewRelic, I only get connectors that are running. Query is:

```sql
SELECT count(*) FROM Metric WHERE metricName = 'cp_kafka_connect_connect_connector_metrics' and clusterName = 'dev-data-pipeline' and connector is not null limit max facet connector, status
```
