### ISSUE TITLE
docker for Mac support

### ISSUE THREAD

**Issue by coughman** [confluentinc/cp-docker-images#83]
As Docker for Mac client becomes the default new client (and perhaps replacing the Docker Toolbox), I suggest we do the following:
- specific docs for Docker Toolbox
- more testing done on Docker Toolbox

**Comment by ackertyson** [comment]
I'm not a Docker expert, but I feel like I'm missing something here. Why wouldn't it work to use a compose file like this on Docker for Mac:

```
version: '2'

services:
  kafka:
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
    image: confluentinc/cp-kafka:3.2.0
    restart: always

  kafka-rest:
    depends_on:
      - kafka
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_REST_LISTENERS: http://kafka-rest:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_HOST_NAME: kafka-rest
    image: confluentinc/cp-kafka-rest:3.2.0
    restart: always

  schema-registry:
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
    image: confluentinc/cp-schema-registry:3.2.0
    restart: always

  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    image: confluentinc/cp-zookeeper:3.2.0
    restart: always
```

...rather than going through the additional step(s) of setting up a VirtualBox host which the use of `network_mode: host` requires?

I am, in fact, using such a setup with Docker for Mac version 17.03.0-ce-mac1 and it appears to work great.....?
