### ISSUE TITLE
cp-kafka on docker swarm advirstises internal listener instead of external

### ISSUE THREAD

**Issue by Ga11u** [confluentinc/cp-docker-images#831]
Description
===========
Hi!
I am trying to deploy a replicated 3 cp-kafka docker instances in a swarm mode on 7 different machines (3 managers and 5 workers) using OpenStack cloud servers (I can deploy all of them without any problem)

The problem comes when I try to use a client external to the network (i.e., from my laptop). I am using confluent-kafka-python to create topics, publish or read messages from kafka. But every time I connect to the broker the client gets the internal listener (e.g., kafka3:9092) instead of the external one (which should be resolved e.g., by tasks.kafka3:39092). Then following connections to the broker fail, as the client tries to reach an incorrect listener IP address.
I followed the Kafka Listeners – Explained (https://www.confluent.io/blog/kafka-listeners-explained/) and set up an internal kafka listener to kafka3:9092 and external listener to tasks.kafka3:39092. Both listeners are set as KAFKA_ADVERTISED_LISTENERS and only the internal at KAFKA_INTER_BROKER_LISTENER_NAME. I am using tasks.kafka3:39092 as the machine is in the docker swarm and it should be resolved externally. I cannot a hostname because I don't have, although it seems it would not solve the problem, as the IP address that the client is receiving is kafka3:9092 which is the internal one (I can see it because the ports are different, the external port should be 39092, not the 9092).

Anyone know which is the error or how should I configure the listeners? What I am doing wrong?
Thank you very much!
There is an extract from the client logs at the end.

This is an extract from the [docker-compose.txt](https://github.com/confluentinc/cp-docker-images/files/4167819/docker-compose.txt)

```
x-network: &network-base
  networks:
    - *network
x-zookeeper: &zookeeper-base
  image: zookeeper
  <<: *network-base
x-kafka: &kafka-base
  image: confluentinc/cp-kafka
  <<: *network-base
  depends_on:
    - zoo1
    - zoo2
    - zoo3

services:                                                                                            
  zoo1:
    <<: *zookeeper-base
    ports:
      - target: 2181
        published: 2181
      - target: 8080
        published: 8085
    volumes:
      - type: volume
        source: zoo1_data
        target: /data
    environment:
      ZOO_MY_ID: 1
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=tasks.zoo2:2888:3888;2182 server.3=tasks.zoo3:2888:3888;2183
      ZOOKEEPER_CLIENT_PORT: 2181
## Other 2 instances of zookeeper are created in the same way (see attached docker-compose file) ##
 kafka1:
    <<: *kafka-base
    ports:
      - target: 9092
        published: 19092
    volumes:
      - type: volume
        source: kafka1_data
        target: /var/lib/kafka/data        
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECT: &zk_hosts "tasks.zoo1:2181,tasks.zoo2:2182,tasks.zoo3:2183"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092 
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://tasks.kafka1:19092,INTERNAL://kafka1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

## Other 2 instances of kafka are created in the same  (see attached docker-compose file) ##
```

How to reproduce
================

1st - Create a stack swarm with 3 different machines (1 manager, 2 workers) and deploy the [docker-compose.txt](https://github.com/confluentinc/cp-docker-images/files/4167819/docker-compose.txt)

2nd - From an external device e.g., a laptop try to create a topic (currently doing with confluent-kafka-python admin), publish or read something.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): confluent-kafka == 1.3.0 && librdkafka == 0.11.6-1.1
 - [x] Apache Kafka broker version: confluentinc/cp-kafka:latest
 - [x] Client configuration:  ({'bootstrap.servers': serviceIPs.kafka_bootstrap_server, 'debug': 'broker,admin'})
 - [x] Operating system: debian
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

Client logs
=========
```
%7|1581011008.148|CREATETOPICS|rdkafka#producer-1| [thrd:main]: CREATETOPICS worker called in state initializing: Success
%7|1581011008.148|ADMIN|rdkafka#producer-1| [thrd:main]: CREATETOPICS: looking up controller
%7|1581011008.148|CONNECT|rdkafka#producer-1| [thrd:kafka3:9092/1004]: kafka3:9092/1004: Received CONNECT op
%7|1581011008.148|STATE|rdkafka#producer-1| [thrd:kafka3:9092/1004]: kafka3:9092/1004: Broker changed state INIT -> TRY_CONNECT
%7|1581011008.148|CREATETOPICS|rdkafka#producer-1| [thrd:main]: CREATETOPICS worker called in state waiting for controller: Success
%7|1581011008.149|ADMIN|rdkafka#producer-1| [thrd:main]: CREATETOPICS: looking up controller
%7|1581011008.149|CONNECT|rdkafka#producer-1| [thrd:kafka3:9092/1004]: kafka3:9092/1004: broker in state TRY_CONNECT connecting
%7|1581011008.149|STATE|rdkafka#producer-1| [thrd:kafka3:9092/1004]: kafka3:9092/1004: Broker changed state TRY_CONNECT -> CONNECT
%7|1581011008.149|CREATETOPICS|rdkafka#producer-1| [thrd:main]: CREATETOPICS worker called in state waiting for controller: Success
%7|1581011008.149|ADMIN|rdkafka#producer-1| [thrd:main]: CREATETOPICS: looking up controller
%7|1581011008.195|BROKERFAIL|rdkafka#producer-1| [thrd:kafka3:9092/1004]: kafka3:9092/1004: failed: err: Local: Host resolution failure: (errno: Bad address)
%7|1581011008.195|STATE|rdkafka#producer-1| [thrd:kafka3:9092/1004]: kafka3:9092/1004: Broker changed state CONNECT -> DOWN
```
