### ISSUE TITLE
confluentinc/cp-kafka takin 40% cpu running in docker

### ISSUE THREAD

**Issue by rafaelleru** [confluentinc/cp-docker-images#844]
I am running Kafka in docker as follows:

```
  # Zookeeper and Kafka from Confluent Plaform.
  # See: https://github.com/confluentinc/cp-docker-images/blob/3.3.x/examples/kafka-single-node/docker-compose.yml
  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:3.3.0
    depends_on:
      - zookeeper
    networks:
      default:
        # alias required for visibility from zookeeper container
        aliases:
          - kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 600000
      TOPIC_METADATA_REFRESH_INTERVAL_MS: 1000
      KAFKA_NUM_PARTITIONS: 20
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    restart: always
```

I have observed that this process runnng in kafka container is taking about 40% of CPU continuously. 

```
java -Xmx512M -Xms512M -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+DisableExplicitGC -Djava.awt.headless=true -Xloggc:/var/log/kafka/zookeeper-gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dkafka.logs.dir=/var/log/kafka -Dlog4j.configuration=file:/etc/kafka/log4j.properties -cp :/usr/bin/../share/java/kafka/*:/usr/bin/../share/java/confluent-support-metrics/*:/usr/share/java/confluent-support-metrics/* org.apache.zookeeper.server.quorum.QuorumPeerMain /etc/kafka/zookeeper.properties
```

Is it normal? I think that this is a lot of CPU for a simple cluster in dev, I am no making a lot of use of this kafka. The CPU is high since the container is created.
